#!/usr/bin/php
<?php
$path = chop(`pwd`);

`ln  $path/zshrc ~/.zshrc`;

`brew install zsh`;
`sudo cp /usr/local/bin/zsh /bin/zsh`;
`brew install reattach-to-user-namespace`;
`chsh -s /bin/zsh`;
`curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh;`;
`brew install autojump`;
#`git clone https://github.com/joelthelion/autojump.git`;

?>


