#!/usr/bin/php
<?php
$path = chop(`pwd`);

`ln -s $path/zshrc ~/.zshrc`;

`brew install zsh`;
`sudo cp /usr/local/bin/zsh /bin/zsh`;
`brew install reattach-to-user-namespace`;
`chsh -s /bin/zsh`;
`curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh`;

?>


