#!/bin/zsh
#
# name     : tmuxen， tmux environment made easy
# author   : Xu Xiaodong xxdlhy@gmail.com
# license  : GPL
# created  : 2012 Jul 01
# modified : 2012 Jul 02
# https://gist.github.com/dmkash/2355219
# http://tmuxp.readthedocs.org/en/latest/about_tmux.html
#

cmd=$(which tmux) # tmux path
session=codefun   # session name

if [ -z $cmd ]; then
  echo "You need to install tmux."
  exit 1
fi

tmux has-session -t ${session}
if [ $? != 0 ]
then
    tmux new-session -s ${session} -n vim -d
# First window (0) -- vim and console
#
    tmux send-keys -t ${session} vim C-m
    tmux split-window -h -p 35 -t ${session}
    tmux new-window -n console -t ${session}
    tmux select-window -t ${session}:1
    tmux select-pane -R
 #   tmux rename-window vim
fi
tmux attach -t ${session}


#   tmux has-session -t development
#   if [ $? != 0 ]; then
#       tmux new-session -s development -n editor -d
#       tmux send-keys -t development 'cd ~/src' C-m
#       tmux send-keys -t development 'vim' C-m
#       tmux split-window -h -t development
#       tmux send-keys -t development:1.2 'cd /var/www/htdocs/' C-m
#       tmux new-window -n console -t development
#       tmux send-keys -t development:2 'cd /var/www/htdocs/' C-m
#       tmux select-window -t development:1
#   fi
#   tmux attach -t development
