#!/usr/bin/php
<?php

function read_stdin()
{
    $fr=fopen("php://stdin","r");   // open our file pointer to read from stdin
    $input = fgets($fr,128);        // read a maximum of 128 characters
    $input = rtrim($input);         // trim any trailing spaces.
    fclose ($fr);                   // close the file handle
    return $input;                  // return the text entered
}

function e($p,$error=false){

    $alert_col="\033[1;32m";
    $normal_col= "\033[0;37m";
    if(!$error){
        if(is_array($p)){
            print_r($p)."\n";
        }else echo $alert_col.'run-> '. $p."$normal_col \n";
    }else{
        echo 'Message error '.$p."\n";
        exit;
    }
}


function get_vim_cmd($path){
    $dir=_BASEDIR;
return <<<EOF
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/vundle/
git clone https://github.com/altercation/vim-colors-solarized.git ~/.vim/bundle/vim-colors-solarized/
curl -S https://raw.githubusercontent.com/poyu007/dotfiles/master/vimrc > $dir/vimrc
curl -S https://raw.githubusercontent.com/poyu007/dotfiles/master/bundles.vim > $dir/bundles.vim
mkdir -p $dir/tmp/
curl -S http://heisoo.oss-cn-qingdao.aliyuncs.com/open/ctags-5.8.tar.gz  > $dir/tmp/ctags-5.8.gar.gz 
cd $dir/tmp/;tar -xvf tags-5.8.gar.gz 
cd $dir/tmp/ctags-5.8/;./configure;make;sudo mv tags /user/bin/ctags
make $dir/tmp/
mv $path/.vimrc $path/.vimrc__old
mv $path/bundles.vim $path/bundles
ln -s $dir/vimrc  $path/.vimrc
ln -s $dir/bundles.vim  ~/.vim/bundles.vim
mkdir -p ~/.vim/backups
mkdir -p ~/.vim/undo
curl -S http://heisoo.oss-cn-qingdao.aliyuncs.com/open/phpctags  > ~/.vim/phpctags
chmod +x ~/.vim/phpctags
EOF;
}


function run_cmds($cmds){
    $cmd_ary = explode("\n", $cmds);
    foreach($cmd_ary as $cmd){
        if(!empty($cmd )){
            e($cmd);
            system($cmd);
        }
    }
}


define('_BASEDIR',$_ENV['HOME'].'/.vim');

e("Process vim setup  ! [y/n] !");
$yorn = read_stdin();
if($yorn == 'y'){
    $cmds = get_vim_cmd($_ENV['HOME']);
    run_cmds($cmds);
}
#`ln  $path/tmux.conf ~/.tmux.conf`;
#`tmux source-file ~/.tmux.conf`;
#
#brew install ctags
# vim +PluginInstall +qall now
?>
