#!/usr/bin/php
<?php
$path = chop(`pwd`);


$cmd_txt = <<<EOF
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/vundle/
git clone https://github.com/altercation/vim-colors-solarized.git ~/.vim/bundle/vim-colors-solarized/
brew install ctags-exuberant
ln -s $path/vimrc  ~/.vimrc
ln -s $path/vimrc.local  ~/.vimrc.local
ln -s $path/  ~/.vim/bundles.vim
mkdir -p ~/.vim/backups
mkdir -p ~/.vim/undo
curl -S http://vim-php.com/phpctags/install/phpctags.phar > ~/.vim/phpctags
chmod +x ~/.vim/phpctags
vim +PluginInstall +qall now
EOF;
$cmd_ary = explode("\n", $cmd_txt);
print_r($cmd_ary);
foreach($cmd_ary as $cmd){
    if(!empty($cmd )){
        system($cmd);
    }
}
#`ln  $path/tmux.conf ~/.tmux.conf`;
#`tmux source-file ~/.tmux.conf`;
#
#brew install ctags
?>
